# adapted from https://github.com/nvim-telescope/telescope.nvim/blob/master/.github/workflows/ci.yml
name: unit tests

on: [push, pull_request]

jobs:
  unit_tests:
    name: unit tests
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-20.04
            url: https://github.com/neovim/neovim/releases/download/v0.7.0/nvim-linux64.tar.gz
          - os: macos-10.15
            url: https://github.com/neovim/neovim/releases/download/v0.7.0/nvim-macos.tar.gz
          # - os: windows-latest
          #   url: https://github.com/neovim/neovim/releases/download/v0.7.0/nvim-win64.zip
    steps:
      - name: prepare
        run: |
          mkdir -p _neovim
          curl -sL ${{ matrix.url }} | tar xzf - --strip-components=1 -C "${PWD}/_neovim"

      - name: run tests
        run: |
          export PATH="${PWD}/_neovim/bin:${PATH}"
          export VIM="${PWD}/_neovim/share/nvim/runtime"
          nvim --version
          make test
