# adapted from https://github.com/nvim-telescope/telescope.nvim/blob/master/.github/workflows/ci.yml
name: unit tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  unit_tests:
    name: unit tests
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            url: https://github.com/neovim/neovim/releases/download/v0.7.0/nvim-linux64.tar.gz
          - os: macos-latest
            url: https://github.com/neovim/neovim/releases/download/v0.7.0/nvim-macos.tar.gz
    steps:
      - uses: actions/checkout@v3
      - name: Prepare
        run: |
          mkdir -p _neovim
          curl -sL ${{ matrix.url }} | tar xzf - --strip-components=1 -C "${PWD}/_neovim"
      - name: Run tests
        run: |
          export PATH="${PWD}/_neovim/bin:${PATH}"
          export VIM="${PWD}/_neovim/share/nvim/runtime"
          nvim --version
          SCNVIM_CI=1 make unit_tests
